name: Emergency virus and disk scan
on: push

jobs:

  emergency:

    runs-on: windows-latest

    steps:

      - name: Check disk

        run: |

        
           echo "::warning title=ChkDsk Warning::This does not automatically fix ANY sorts of emergency, likewise the virus scan can. When all checks are finished, you may need a step in your workflow to fix everything." 
           chkdsk
           echo " "
           echo "::notice title=Disk check::Exit code $LASTEXITCODE."

           

      - name: Preform Windows Security virus scan

        run: |
          echo "Scan begins in 10 seconds. DO NOT CANCEL THE WORKFLOW."
          Start-Sleep -Seconds 10
          echo "Scanning for viruses... Please do not cancel the workflow."
          Start-MpScan -ScanType QuickScan
          echo "Done!"
          echo "Uninstalling all detected viruses... Please do not cancel the workflow."
          Remove-MpThreat
          echo "Uninstalled malware!"

          echo "::notice title=Virus check::Scan finished. If exit code is 0, you are no longer in an emergency. You are now free to cancel the workflow if you want to."
