name: Emergency virus and disk scan
on: push

jobs:

  emergency:

    runs-on: windows-latest

    steps:

      - name: Check disk

        run: |

        

           chkdsk

           echo "::notice title=Disk check::Exit code $LASTEXITCODE."

           

      - name: Preform Windows Security virus scan

        run: |

          echo "Scanning for viruses..."
          Start-MpScan -ScanType QuickScan -Debug
          echo "Done!"
          echo "Uninstalling all detected viruses..."
          Remove-MpThreat
          echo "Uninstalled malware!"
          echo "::notice title=Virus check::Scan finished. If exit code is 0, you are no longer in an emergency."
